### PR TITLE
Implement Log in Throw Exception Method

### PR DESCRIPTION
**Pull request by jdajes3**
This PR implementa Log in Throw Exception Method

### Check out this Pull Request Locally
```
git fetch upstream pull/86/head:ImplementLog
```

### CODE REVIEW

**Comment by mgwelch** [comment]
I'm too late, but I don't think it's appropriate for a library to log errors. You're job is to communicate errors to the client of your library (via error codes and/or exceptions) and let them decide what to do. Perhaps they want to log, perhaps they don't. @buldrinie  @jdajes3

**Comment by buldrinie** [comment]
I agree that logging should not be responsibility of the library and if you see it from an SDK point of view could be a facility provided for the developer. The consumer could decide to disable it through a config file parameter and implement its own logging system/not logging at all or use it as is, considered a troubleshooting point for the custom application.

**Comment by mgwelch** [comment]
I think of the .Net framework. All errors are communicated to me thru exceptions. There is no place where Microsoft expects you to hook up a logging system to figure out your issues. It seems  that using logging would be an excuse to not make your exceptions/errors as valuable as they need to be. 

If there is something happening in the background asynchronously, you could consider adding an Error event that the client could attach and event handler to so that they gain visibility into to the issues.

Having said that, I'm still fine with you making whatever decisions you think are best. I'm just providing a different perspective.

**Comment by buldrinie** [comment]
Sure, all exceptions remains in place. The SDK log is just an additional "safe" layer that could be useful to troubleshoot when the exceptions are not handled or logged in any place by the consumer application.

**Comment by mgwelch** [comment]
Is logging turned off by default? I don't think a client would want things written to disk without their explicit knowledge/consent.

**Comment by mgwelch** [comment]
I was looking more closely at the log messages. The issue with logging is

1. If the client decides to log, now they'll get 2 log messages for every exception you throw. Original Metasys code is littered with these sorts of issues. We quickly learned: 1) if you have enough context to figure what is going wrong and correct it then go ahead and log it, correct the issue but don't throw an exception or 2) don't log it but go ahead and throw an exception. You only do one or the other; else you just complicate debugging, not enhance it.
2. The messages aren't helpful. They aren't even correct.

Here's the first example when a 404 happens: ""An error occured while getting Http Status Code"

There was no error getting the status code. The error was that the resource you asked for was not found. For this log message to be useful you'd maybe want to write something like "The resource asked for could not be found by the server". But even with that message it's hard to understand how this is a useful debugging/diagnostic tool when you are already throwing an exception that conveys the exact same information.

The next message: "An error occured while parsing Flurl exception"

Again, the error wasn't with parsing a Flurl exception. The error was parsing the response from the server. So a message like this might be useful: "A response was returned by the server that could not be understood."

Finally, the time out exception: ""An error occured while getting timeout Exception in FlurlHttp"

There was no error trying to get a timeout. The error was that the request timed out.

**Comment by mgwelch** [comment]
The readme doesn't mention anything with how to disable logging.

**Comment by buldrinie** [comment]
Michael, in the current release version 3.2.0 the logger is just provided as a facility to be used in the consumer application. No logging is performed by the library, there was an issue with the initialization of the class and we didn't include this PR.  At this point, we could just move the classes of the Logging namespace in the example apps to have a demo on how exceptions should be trapped. My only concern is about the Exceptions that could be lost if not logged by consumer applications. I'll set a time slot to discuss more in depth this.

**Pull request merged**
