### PR TITLE
Phase3 methods

### PR DESCRIPTION
**Pull request by SavannahEvans**
New Client Methods:
* GetNetworkDevices and GetNetworkDevicesAsync
* GetNetworkDeviceTypes and GetNetworkDeviceTypesAsync
* GetObjects and GetObjectsAsync

New Class:
* MetasysObject - holds basic information about a Metasys object

Fixes:
* Method headers
* GetObjectIdentifier to use JToken to eliminate need for char trimming

### CODE REVIEW

**Comment by SavannahEvans** [comment]
GetObjects needs to be updated to recursively get and return all children. Need advice on what fields to include in MetasysObject.

**Comment by SavannahEvans** [comment]
The MSSDA bulletin specified that if no value for the item reference (in TraditionalClient's case the GUID) that the top level device should be used as the parent. I do not see an easy way of implementing this given the current API.

**Comment by mgwelch** [comment]
@SavannahEvans sorry I didn't provide more guidance on this. Probably the best way to handle devices and objects is to implement a fetch process which grabs all the pages of objects or devices for a particular device. This may be rather long running so we may want to cache it locally on the file system. A customer would only need to do a new fetch if/when they add/delete objects/devices.

This is probably the best we can do until 11.0 or 11.1 when there is a plan to add more query parameters to /objects /devices

**Comment by buldrinie** [comment]
@SavannahEvans, based on what I can see from the Metasys Launcher we could get the site root ID using a canonical FQR prefixed with the host, e.g. WIN2016-VM2:WIN2016-VM2/$site.  You can see below an example of the site object. @mgwelch, please we need confirmation if this is the preferred and reliable way to fetch the root.
site

**Comment by mgwelch** [comment]
@buldrinie It depends on what you consider the root. The root device is `WIN2016-VM2:WIN2016-VM2`.

What you referenced is the "site object", which contains some global site information. But it's not the root of the all item tree. The `$` means it's a hidden object. We don't typically expose it directly to users

**Comment by buldrinie** [comment]
My idea was to expose the entire objects tree as in the navigator, but according to @mgwelch comments I think that makes sense to filter out only objects that are usable/relevant for the API. Fetching the NetworkDevices we have a starting point without knowledge of the specific GUID/FQR.
tree

**Comment by SavannahEvans** [comment]
Issue #30 is for caching GetObjectIdentifier results. Since it is a smaller task I will focus on it for now. Once this is working I can implement caching for these calls as well.

**Comment by mgwelch** [comment]
> Issue #30 is for caching GetObjectIdentifier results. Since it is a smaller task I will focus on it for now. Once this is working I can implement caching for these calls as well.

This is fine, but thru the API we really wanted to encourage users to always use the object identifier (not the FQR) to uniquely identify things. So for an Excel app user, for example, they should be able to lookup object identifiers at design time and then hard code the object ids into their apps so that they never need to fetch object identifiers again, and therefore you wouldn't need a cache.

Why do we want to encourage the use of object ids? Because once the work is complete they will be the only truly immutable unique ids in the system. 

Now it'll probably be years before we achieve that vision in Metasys so relying on FQRs will be a requirement for a while. But we wanted to start getting people thinking in terms of GUIDs

**Pull request merged**
