### PR TITLE
Phase1 Updates

### PR DESCRIPTION
**Pull request by SavannahEvans**
Changes:
* Edited the MetasysHttpExceptions to not derive from Flurl exception classes.
* Edited xml headings to all Phase 1 related classes and objects including MetasysClient, IMetasysClient, Variant, VariantMultiple, ApiVersion, and AccessToken.
* Removed automated Flurl exception management to give better control over exception handling in MetasysClient.
* ReadProperty now returns null if no resource is found and no exceptions are thrown.
* Fixed error handling by added missing exception catches on multiple methods, fixed missing null reference check in ReadPropertyMultiple.
* Improved upon existing testing structure and added missing tests for Metasys Exceptions.

Note: Phase 2 methods still need the improvements the phase 1 methods now have. README update will come in a separate pull request.

### CODE REVIEW

**Comment by mgwelch** [comment]
> * ReadProperty now returns null if no resource is found and no exceptions are thrown.

What is the return type of ReadPropety? If it's a structure (like Variant) then it's good to make it nullable (Variant?) which returns an optional and requires the consumer check for null before they can use it. 

Returning null when the return type is a class is error prone. The consumer normally won't right code to check for null. In C# 8 we can use nullable reference types which will help mitigate this issue and at least issue a warning for users that they are not handling possible null values.

**Comment by buldrinie** [comment]
After a more detailed analysis I think we could just raise an Exception also for HttpNotFound response code of ReadProperty. The method assumes that you know in advance the GUID and the attribute you are reading and this information is supposed to be obtained exploring the object tree. There is no need to use this method for "exists" logic performing null check. The only case where we can arrive here is if the item was removed from Metasys and the client App cached locally the GUID without refreshing the elements: this is clearly an Exception.
However, an extra attention is needed for ReadPropertyMultiple: this method has a dependency on ReadProperty and we could have the case where different objects don't share the same common attributes set. In this scenario we get back a NotFound and need to be handled without Exception, simply without returning the missing attribute. So we could just keep a private signature for ReadProperty that doesn't throw exception and returns null, only for internal use of ReadPropertyMultiple.

**Comment by mgwelch** [comment]
@buldrinie my recommendation would be to make the return type from these calls be structs (not classes) and then make them nullable (My original template for these methods all returned structs for this very reason). What is actually returned then is an Optional<T> where T is your return type.

This allows you to keep the consistent null return when not found, and forces the consumer to check for null. (It clearly communicates to the consumer that null is an expected return value)

**Comment by buldrinie** [comment]
@mgwelch, this is addressed in this commit https://github.com/metasys-server/basic-services-dotnet/commit/b9ba2964d47fa4d1751d80ee025e9ec7b8fddec0. Please let me know if you want to keep the throwsNotFoundException bool parameter to control the Exception.

**Comment by mgwelch** [comment]
If you are okay with the use of the Optional<Variant> (as it appears you are), then I think using `null` (and documenting it as such) as the not found value is enough. No exception is every needed, and the boolean parameter isn't needed either. I think I'd be inclined to remove it.

**Comment by buldrinie** [comment]
@mgwelch, I removed the Boolean parameter in this commit https://github.com/metasys-server/basic-services-dotnet/commit/480d3eb1d57288010d15dc7291c6e22189d689d5. My doubt for the nullable struct is that makes the method usage heavier with the use of .Value to retrieve the result and we can't use inheritance in case we need to extend the struct, but as soon as we don't have blocking limits for me it's ok.

**Comment by mgwelch** [comment]
I can support your previous decision if you wish to reverse these recent changes. I only weighed in because it seemed like we were getting a bit of a difference in how ReadProperty and ReadPropertyMultiple would work. And it seemed using nullable struct made it easier to make them work more the same. 

I would not strongly object to the way you had it. 

> My doubt for the nullable struct is that makes the method usage heavier with the use of .Value to retrieve the result

Yeah, but it's not really heavier. If the values in ReadPropertyMultiple could be `null` then every place a consumer is checking to see if the optional has a value they would have to be checking for null anyway. All the use of Nullable<T> is doing is making it explicit that you have to do the check. (Note: they should never use `.Value` without checking if there is a value. `GetValueOrDefault()` is often a good choice instead. Or extension methods that can do `.Map` or `.GetValueOrElse(T elseValue)`. 

> and we can't use inheritance in case we need to extend the struct, 

I'd be very careful even considering inheritance. Using delegation and interfaces is often better than inheritance (in terms of maintainability and potential unforeseen errors and more difficult testing)

**Pull request merged**
